# ASP.NET Core (.NET Framework)

trigger:
 branches:
  include:
    - master
 paths:
  include:
    - 'LorryLogAdmin/*'
   

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  project: '**/LorryLogAdmin/LorryLogAdmin.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Development'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(project)'    
    arguments: '--output admin_output'
    modifyOutputPath: true
    zipAfterPublish: True

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'LorryLogAdminServiceConnection'
    appType: 'webApp'
    WebAppName: 'lorrylogadmin'
    packageForLinux: '$(Build.DefaultWorkingDirectory)/admin_output/*.zip'

